### PR TITLE
Create CONTRIBUTING

### PR DESCRIPTION
**Pull request by jamal919**
Added a markdown copy of git-cheat

### CODE REVIEW

**Comment by jreniel** [comment]
Can we all take a look at this and approve/suggest edits?

**Comment by jamal919** [comment]
Following changes -
1. CONTRIBUTING is renamed to CONTRIBUTING.md so that markdown is displayed in github
2. merge --squash is added
3. Markdown for the terminal commands are added

This branch has no conflit with the base branch - so should be straightforward to merge once everyone agrees. 

I am not able to merge it, as github is showing me that I do not have write access to merge this pull request. 

Thanks.

**Comment by jreniel** [comment]
@jamal919 You should have write permissions now. Try again so we can confirm.

**Comment by jamal919** [comment]
Squash and merged. Thanks.

**Pull request merged**
