### PR TITLE
Calculate pressure in fabm_schism and use windvel

### PR DESCRIPTION
**Pull request by platipodium**
This PR lets fabm models use wind velocity and internal pressure.

### CODE REVIEW

**Comment by platipodium** [comment]
@josephzhang8 Please review pressure calculation

**Comment by platipodium** [comment]
@josephzhang8 Jan updated the pressure calculation, it would be great if you had a look and then merged this PR. Thx

**Review by josephzhang8 — COMMENTED** [review]
Hi Carsten, Jan:

In calculating the hydrostatic pressure, I suggest using the distance to surface:

fs%pres(k,i)=rho0*grav*abs(ze(nvrt,i)-ze(n,i))*1.e-4

If you want to add atmos pressure, u can use pr2(npa), e.g. like sum(pr2)/i34*1.e-4 (pr2 is in Pa)

**Comment by platipodium** [comment]
I implemented @josephzhang8 suggestions for the pressure calculation and *added atmospheric pressure*..  @janko-om please review

**Review by janko-om — APPROVED** [review]

**Pull request merged**
