### PR TITLE
Match MPI_Finalize behavior to MPI_Init

### PR DESCRIPTION
**Pull request by PhilMiller**
For the benefit of library users of SCHISM, it should only call `MPI_FInalize` if it 'owns' the MPI state. If the client code passed SCHISM a communicator, then that client code owns the process's MPI. In that case, SCHISM should not finalize MPI, which may corrupt the client's state, causing a crash or other unexpected behavior near the end of the run.

### CODE REVIEW

**Comment by PhilMiller** [comment]
This change was inspired by NWM work on integrating code from ESMF that also invariably called `MPI_Finalize` whether we wanted it to or not.

**Comment by josephzhang8** [comment]
@danishyo: how would this change impact PDAF?

**Comment by josephzhang8** [comment]
Thx @PhilMiller; we understand your reasoning. I just wanted to make sure it works for another ESMF app.

**Comment by danishyo** [comment]
I don't use it in PDAF, but there is an interface in schism_bmi.F90 (parallel_finalize)

**Comment by josephzhang8** [comment]
@platipodium: can u plz check whether it's necessary to include parallel_finalize in schism_bmi.F90? Not a big deal, but with Phil's change, it won't do anything when the communicator is inherited. 

I'll go ahead and accept Phil's PR. Thx

**Comment by jduckerOWP** [comment]
@PhilMiller @josephzhang8 is it simpler potentially to just implement some small source code modifications to that SCHISM subroutine to just bypass the `MPI_Finalize` method if the BMI flag is on for SCHISM? Just a general thought here but regardless great work on this Phil!

**Comment by PhilMiller** [comment]
Thanks for the incredibly quick review and merge on this @josephzhang8 

@danishyo What's the `schism_bmi.F90` you mentioned? Is there another BMI implementation for SCHISM besides the one that Jason developed?

**Comment by josephzhang8** [comment]
schism_bmi.F90 was written by @platipodium for NUOPC/UFS.

**Comment by PhilMiller** [comment]
Where does that implementation live? I'd like to compare it with what we have in development.

**Comment by josephzhang8** [comment]
See: https://github.com/schism-dev/schism-esmf/blob/master/src/schism/schism_bmi.F90

**Review by jduckerOWP — COMMENTED** [review]
@PhilMiller All of these changes are simple and straightforward to follow. I just finished reviewing the changes in the document. I really like how you've integrated a dynamic variable to account for whether or not an MPI communicator has already been allocated to initialize the SCHISM MPI fields using the `mpi_comm_dup` method (NextGen or any coupled framework for that matter) or just the standalone model approach where it assigns its own MPI communicator within it's runtime environment. @josephzhang8 thanks for migrating these changes so quickly to schism-master branch.

**Pull request merged**
