### PR TITLE
Merges with LR team updates

### PR DESCRIPTION
**Pull request by mpezerat**
Following updates follow
-Lavaud et al. 2022 JGR Earth surface DOI 10.1029/2021JF006466
-Pezrat et al. 2022 JGR Ocean DOI 10.1029/2021JC018108
-Martins et al. 2022 OM (in prep)

commit 2c9a47694fc6c779e0e8af23f0c62be2015101b5
Author: mpezerat <pezeratm@gmail.com>
Date:   Wed Apr 20 17:10:49 2022 +0200

    [SCHISM] Adds outputs and fixes bugs

    - misc_subs.F90 : fixes a mistake in wave direction computation within GM wbl subroutine
    - schism_init.F90 : Extends iof_wwm size and init sds variable
    - schism_step.F90 : Adds iof_wwm outputs
    - wwm_specint.F90 : Fixes a mistake in INT_SHALLOW_SOURCETERMS subroutine
    - wwm_sourceterms.F90 : Changes call to COMPUTE_SDS subrtoutine
    - wwm_coupl_selfe.F90 : Fixes a mistake in non-conservative breaking wave force computation

commit b9c68a29d4d51e5ac335aa168bd8a42fc06fcf63
Author: mpezerat <pezeratm@gmail.com>
Date:   Thu Apr 7 12:19:27 2022 +0200

    [SCHISM] Fixes OLDIO outputs

    - scribe no more compiled when using OLDIO
    - fixes a little variable assignment error in WWM

commit 491b6a6bb042cfea03c59a896672116128b748bc
Author: mpezerat <pezeratm@gmail.com>
Date:   Wed Apr 6 18:52:53 2022 +0200

    [SCHISM] Updates turbulence settings with itur=4
             Fixes mistakes in wave-current bottom stress computation

commit 5b96d86969c447a10e21df1733a4087af0ec8cc0
Author: mpezerat <pezeratm@gmail.com>
Date:   Wed Apr 6 14:54:52 2022 +0200

    [WWM] Updates SHOWEX formulation for dissipation by bottom friction

    - Takes into account a spatially varying median grain size

commit 440e151b509a216f2823e5884e6193a989f9442d
Author: mpezerat <pezeratm@gmail.com>
Date:   Wed Apr 6 12:22:45 2022 +0200

    [WWM] Updates roller model and vortex force formalism

    - For the roller model, we now solve Eq. 40 of Uchiyama et al. (2010)
    - Modifications of the Stokes drift velocity and the radiation stresses follow
    - Updates continuity equation accounting for mass transport by rollers
    - Updates non-conservative breaking wave force accounting for rollers and whitecapping
    - Adds streaming wave force
    - Updates VF computations using implicit solver

commit b481d02cb9d9d56d635a5f70e6910c2d0bc43469
Author: mpezerat <pezeratm@gmail.com>
Date:   Thu Mar 31 12:35:07 2022 +0200

    [WWM] Adds Westhuysen's formulation for implicit solver

### CODE REVIEW

**Review by josephzhang8 — COMMENTED** [review]
This file should not be merged.

**Comment by josephzhang8** [comment]
Sorry, still learning how to use comment in github...


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Review by josephzhang8 — COMMENTED** [review]
I'll approve the changes first but will revert a few files (include*, schism_driver and Makefile) and do further changes for some others. Thx Marc.

**Comment by mpezerat** [comment]
Hi Joseph,
Thank you for reviewing the updates. Regarding the outputs, you can reverse
the changes I made, it's simply that I was a bit lost regarding my own
subroutines for test case post-processing as I used to work with schout
files.
By the way, I get a new position at the Hydrographic and Oceanographic
French Office, I will still be in touch with LR team, but I will be less
involved in SCHISM dev... Anyway thanks for your help, I learned a lot with
SCHISM and WWM !
Marc

Le mer. 27 avr. 2022 à 15:22, Joseph Zhang ***@***.***> a
écrit :

**Comment by aronroland** [comment]
Hi Marc, Joseph, 

 

as far I am concerned I think this is all fine. Wish u all the best Marc. 

 

Cheers

 

Aron

 

Von: mpezerat ***@***.***> 
Gesendet: Donnerstag, 28. April 2022 10:56
An: schism-dev/schism ***@***.***>
Cc: Aron Roland ***@***.***>; Review requested ***@***.***>
Betreff: Re: [schism-dev/schism] Merges with LR team updates (PR #65)

 

Hi Joseph,
Thank you for reviewing the updates. Regarding the outputs, you can reverse
the changes I made, it's simply that I was a bit lost regarding my own
subroutines for test case post-processing as I used to work with schout
files.
By the way, I get a new position at the Hydrographic and Oceanographic
French Office, I will still be in touch with LR team, but I will be less
involved in SCHISM dev... Anyway thanks for your help, I learned a lot with
SCHISM and WWM !
Marc

Le mer. 27 avr. 2022 à 15:22, Joseph Zhang ***@***.*** <mailto:***@***.***> > a
écrit :

**Comment by josephzhang8** [comment]
Thx Aron, Marc. And congrats, Marc for your new position!


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Comment by josephzhang8** [comment]
Hi Marc et al.:

I noticed you added the turbulence from VOR in itur=4 (GOTM) only. It's usually a pain to compile with GOTM, and we usually use itur=3. Could you add it in itur=3 also? Thx.


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Comment by jamal919** [comment]
I am closing this PR as the changes are incorporated by 40baa99e2299c440381045d3692784a0e8cdaaf3, 6524e19c5d5edca7d5c60eb4234c7d44bfdbe015, 3906b0cec4859b51910add7f1a39a21df7dc160e, 567b61235fa9a815ac7b4fa19984fca42fa9f381, 73f7e1b36f16987fab0373baac012074db41f25c, ff5ad7546c5cec721e83f4ec55484d43e5a160bb, 9b711aff8ee2c382e24e175a3b5b2e9a0b4761b5

**Pull request closed without merging**
