### PR TITLE
Cmmb

### PR DESCRIPTION
**Pull request by pvelissariou1**
I have modified the schism/src/CMakeLists.txt, schism/src/Driver/CMakeLists.txt and added the schism/cmake/module/FindParMETIS.cmake to allow the use of externally built ParMETIS/METIS/GKlib libraries.
The user can supply from the CMake command line or from the environment one of the variables:
PARMETIS[_]HOME, PARMETIS[_]ROOT, PARMETIS[_]PATH to supply the location of the pre-compiled ParMETIS libraries.
If the libraries and headers are not found the compilation proceeds using the SCHISM's internal library as normal.
If the above variables are not defined the compilation of SCHISM proceeds as usual.
Read the notes for ParMETIS in schism/src/CMakeLists.txt and schism/cmake/module/FindParMETIS.cmake for additional information.

SCHISM has been successfully compiled using this configuration and the latest version of ParMETIS (https://github.com/KarypisLab/ParMETIS).

### CODE REVIEW

**Comment by platipodium** [comment]
Thx @pvelissariou1 .  I am very much in FAVOR of using an external parametrische amd will test on my systems.   
there were, however, good reasons for disabling the online partitioning with NOPARMETIS, so we need that flag to be reintroduced.  As far as I was informed about their license terms, we cannot use online parmetis in production context .  This problem might also affect WW3…

**Comment by platipodium** [comment]
> The ParMETIS package is copyrighted by the Regents of the 
 University of Minnesota. It can be freely used for educational and 
 research purposes by non-profit institutions and US government 
 agencies only. Other organizations are allowed to use ParMETIS 
 only for evaluation purposes, and any further uses will require prior 
 approval.

**Comment by pvelissariou1** [comment]
Thank you @Lemmen, Carsten ***@***.***> , ParMETIS at this
point affects both WW3 and SCHISM. WW3 developers are moving away from
ParMETIS, I believe that are looking at PT-SCOTCH (
https://www.labri.fr/perso/pelegrin/scotch/,
https://gitlab.inria.fr/scotch/scotch).
Because of the license restrictions of ParMETIS, as you also mentioned, the
library has been removed from CoastalApp.
The build scripts in CoastalApp have been modified to allow the user to use
externally compiled ParMETIS to be used
with both WW3 and SCHISM (this is a temporary workaround for ParMETIS in
CoastalApp). With this PR request for ParMETIS,
SCHISM can also use an external ParMETIS without affecting its
functionality or its capability to use the internal ParMETIS.
My thinking was to allow the use of  an external ParMETIS, in CoastalApp so
the application can be used
with the current status of WW3 and SCHISM + ParMETIS without issues to the
user.
@Lemmen, Carsten ***@***.***> , as you mentioned, ParMETIS
should be removed. I am following the WW3 development status on this issue.
@Y. Joseph Zhang ***@***.***> , @Carsten Lemmen
***@***.***> please check if this PR works in your side and I
will also check if this work
on our side with the SCHISM test cases we have (compilation goes smoothly
and without errors). If everything goes well, please accept
this PR.

Later today, I'll update CoastalApp with the latest build scripts. I'll
keep you posted.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
Thx Takis. The code will only look for the partition map (partition.prop) if NO_PARMETIS is on, so I think we'll have to add that flag if we want to bypass PM.

-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Comment by pvelissariou1** [comment]
So, to understand. We can pass a NO_PARMETIS flag to cmake (may be to schism/src/CMakeLists.txt) to bypass ParMETIS all together. I understand that such a flag does not exist currently in the SCHISM code. At theend we will have the following options: a) NO_PARMETIS, b) to use an external ParMETIS and c) to use SCHISM's internal ParMETIS. In any case, I need to maintain the capability of allowing the use of an externally built ParMETIS in CoastalApp, otherwise the application will break (WW3 dependency). Your thoughts?

**Comment by josephzhang8** [comment]
Hi Takis:

You can find NO_PARMETIS in cmake/SCHISM.local.build. I'm fine with any of the 3 options, as they should all work. Thx.


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Comment by pvelissariou1** [comment]
I fetched the latest sources and now I see the NO_PARMETIS option. I'll
update the files in the PR to include the NO_PARMETIS option and
in this case we will have all options available. I'll update CostalApp to
use the latest version of schism as well.
Thank you Joseph.

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: ***@***.***

**Comment by josephzhang8** [comment]
Thank you Takis!


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Comment by platipodium** [comment]
Thanks Takis.  Indeed we need the three options. We'll test this and report back.

**Comment by pvelissariou1** [comment]
The files src/CMakeLists.txt src/Driver/CMakeLists.txt inclule the NO_PARMETIS flag.
SCHISM compiles properly with no errors.
In the project's languages CXX has been added.

**Comment by platipodium** [comment]
There seems to be a problem (maybe only in the diagnostic output) with ParMETIS

``
cmake ../src -DNO_PARMETIS=OFF

### Configuring Driver
-- Building SCHISM without ParMETIS lib
```
produces an exectutable that (correctly) includes parmetis refs.  So the info message during CMake is wrong.

**Comment by platipodium** [comment]
I am confused @pvelissariou1  on how to set an external parmetis dir and how this affects the internal processing:

when I issue ` cmake -DCMAKE_PARMETIS_DIR=/usr/local`the setting does not propagate correctly to (child?) parmetis variables.

```
cat CMakecache.txt |grep -i metis
CMAKE_PARMETIS_DIR:UNINITIALIZED=/usr/local
GKLIB_PATH:PATH=/home/lemmen/devel/schism/schism/src/ParMetis-4.0.3/metis/GKlib
//path to METIS
METIS_PATH:PATH=/home/lemmen/devel/schism/schism/src/ParMetis-4.0.3/metis
NO_PARMETIS:BOOL=OFF
//Path to ParMetis which defaults to /src/PARMETIS_VER in the schism
PARMETIS_DIR:PATH=/home/lemmen/devel/schism/schism/src/ParMetis-4.0.3
PARMETIS_HOME:UNINITIALIZED=/usr/local
//Version and relative path to Parmetis library inside /src.
PARMETIS_VER:STRING=ParMetis-4.0.3
ParMETIS_BINARY_DIR:STATIC=/home/lemmen/devel/schism/schism/build/ParMetis-4.0.3
ParMETIS_IS_TOP_LEVEL:STATIC=OFF
ParMETIS_SOURCE_DIR:STATIC=/home/lemmen/devel/schism/schism/src/ParMetis-4.0.3
metis_LIB_DEPENDS:STATIC=general;m;
parmetis_LIB_DEPENDS:STATIC=general;metis;general;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;general;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so;
```

**Comment by josephzhang8** [comment]
@platipodium: NO_PARMETIS=OFF would turn ON PM (double negative).

**Comment by pvelissariou1** [comment]
@Lemmen, Carsten ***@***.***> Let me check, it works here as
expected.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: ***@***.***

**Comment by pvelissariou1** [comment]
@Lemmen, Carsten ***@***.***> The variables starting with
CMAKE are cmake's internal/reserved variables:

From the CMake documentation

CMake reserves identifiers that:

    begin with CMAKE_ (upper-, lower-, or mixed-case), or

    begin with _CMAKE_ (upper-, lower-, or mixed-case), or

    begin with _ followed by the name of any CMake Command.


*For ParMETIS in SCHISM I have setup the system as follows (from:
schism/src/CMakeLists.txt)*
  ### The user can supply *one of the following variables* to provide the
full path
  ### to the installed ParMETIS librarie(s):
 * ### (a) Via the cmake command line:*
  ###   -DPARMETIS_HOME=PATH, or -DPARMETISHOME=PATH, or
  ###   -DPARMETIS_ROOT=PATH, or -DPARMETISROOT=PATH, or
  ###   -DPARMETIS_PATH=PATH, or -DPARMETISPATH=PATH
  *### (b) Via the environment:*
  ###   PARMETIS_HOME=PATH, or PARMETISHOME=PATH, or
  ###   PARMETIS_ROOT=PATH, or PARMETISROOT=PATH, or
  ###   PARMETIS_PATH=PATH, or PARMETISPATH=PATH
 * ###  We keep PARMETIS_DIR for internal use only.*


IMPORTANT: In the language list I have added CXX (for ParMETIS)
set(comp_lang_list C Fortran)
project(SCHISM LANGUAGES ${comp_lang_list} CXX)


*The user can pass either from the cmake command line or from the
environment one of the variables in red.*
*To compile SCHISM I used:*
cmake -S ~/CSDL/Repos/del/CoastalApp/SCHISM/schism/src -B
~/CSDL/Repos/del/CoastalApp/SCHISM/build -DCMAKE_VERBOSE_MAKEFILE=TRUE
-DCMAKE_Fortran_COMPILER=mpifort -DCMAKE_CXX_COMPILER=mpicxx
-DCMAKE_C_COMPILER=mpicc -DOLDIO=ON -DUSE_WW3=ON -DPREC_EVAP=OFF
*-DPARMETIS_HOME=~/CSDL/Repos/del/CoastalApp/THIRDPARTY_INSTALL*

*and in the build/CMakeCache.txt the following are defined:*
//ParMETIS GKlib include directory
//ParMETIS METIS include directory
METIS_INCLUDE_FILE:FILEPATH=/home/takis/CSDL/Repos/del/CoastalApp/THIRDPARTY_INSTALL/include/metis.h
//METIS library
METIS_LIBRARY:STRING=/home/takis/CSDL/Repos/del/CoastalApp/THIRDPARTY_INSTALL/lib/libmetis.a
NO_PARMETIS:BOOL=OFF
//Path to already compiled ParMetis external library.
PARMETIS_DIR:PATH=/home/takis/CSDL/Repos/del/CoastalApp/THIRDPARTY_INSTALL
PARMETIS_HOME:UNINITIALIZED=~/CSDL/Repos/del/CoastalApp/THIRDPARTY_INSTALL
//ParMETIS Found
ParMETIS_FOUND:BOOL=TRUE
//ParMETIS include paths
ParMETIS_INCLUDE_DIRS:STRING=/home/takis/CSDL/Repos/del/CoastalApp/THIRDPARTY_INSTALL/include
//ParMETIS ParMETIS include directory
ParMETIS_INCLUDE_FILE:FILEPATH=/home/takis/CSDL/Repos/del/CoastalApp/THIRDPARTY_INSTALL/include/parmetis.h
//ParMETIS library paths
ParMETIS_LIBRARIES:STRING=/home/takis/CSDL/Repos/del/CoastalApp/THIRDPARTY_INSTALL/lib/libparmetis.a;/home/takis/CSDL/Repos/del/CoastalApp/THIRDPARTY_INSTALL/lib/libmetis.a;/home/takis/CSDL/Repos/del/CoastalApp/THIRDPARTY_INSTALL/lib/libGKlib.a
//ParMETIS library
ParMETIS_LIBRARY:STRING=/home/takis/CSDL/Repos/del/CoastalApp/THIRDPARTY_INSTALL/lib/libparmetis.a
//ADVANCED property for variable: METIS_INCLUDE_FILE
METIS_INCLUDE_FILE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: METIS_LIBRARY
METIS_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: ParMETIS_INCLUDE_FILE
ParMETIS_INCLUDE_FILE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: ParMETIS_LIBRARY
ParMETIS_LIBRARY-ADVANCED:INTERNAL=1

I have also built SCHISM with the "NO_PARMETIS=ON" option
Everything seems to work as expected.
I hope this explanation helps. Maybe this can be included in the
documentation?

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: ***@***.***

**Comment by platipodium** [comment]
@pvelissariou1  OK, got it working.

**Review by platipodium — APPROVED** [review]

**Comment by josephzhang8** [comment]
Thx, Takis, Carsten! I've used git cmd's to merge this PR into master. Plz re-test. Thx.

**Comment by pvelissariou1** [comment]
Hello Joseph

Please remove the lines:
line 83: cp $(SCHISM_BUILD_DIR)/lib/libmetis.a $(DESTDIR)
line 84: cp $(SCHISM_BUILD_DIR)/lib/libparmetis.a $(DESTDIR)
from the schism-esmf/Makefile.
I have submitted a PR to schism-esmf

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: ***@***.***

**Comment by josephzhang8** [comment]
I see. In the future, we may avoid the confusion by changing it to PARMETIS=..., but I agree with u.

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Pull request closed without merging**
