### PR TITLE
Added time variable units, standard_name and axis attributes

### PR DESCRIPTION
**Pull request by platipodium**
I will be making more changes improving UGRID standard compatibility in this branch. See [http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#coordinate-system](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#coordinate-system) for reference.

So far, the following additions have been made in scribe_io.F90

- attributes of the time variable, including a proper isostring time reference for the units attribute.  
- metadata field for CF required mesh_topology
- metadata field for UGRID required CRS/grid_mapping (only ics=2)
- all 2D/3D variables handled

Is there anything that speaks against these additions?

Yet not added are
- smart auto _FillValue depending on xtype
- configurable option to include/exclude mesh info in 3D output (to save disk space)
- ...

Current bugs
- output is complete for lat_lon only (ics=2).  Wrong CRS and units are written in other cases.  How do we get the mapping information here?  This should only be available in the preprocessing and needs to be transferred to output (do this later)

### CODE REVIEW

**Comment by platipodium** [comment]
Tested with various constellations of utc and dates/times.  Missing yet is support for fractional utc and hour specs (currently simply integer-truncated)

**Comment by josephzhang8** [comment]
@platipodium:

Thx for your work. None of my scripts use that info so in general I'm fine adding UGRID decor there. 

My comments:
1) x,y units are not always lon, lat so this is misleading;
2) I think you can easily accommodate the utc_start or start_hour being real in those write statements?
3) Calculation of side/elem centers is wrong across lon jumps (that's why mu scripts calculate these separately)
4) The fact that we have split the outputs into multiple pieces already violates UGRID, so I really don't see the point of overloading 3D outputs with metadata and static arrays (file size). It's more than sufficient to have this in out2d*.nc.

**Comment by platipodium** [comment]
> None of my scripts use that info so in general I'm fine adding UGRID decor there.

Our visualisation pipeline requires this.  Obligatory, not decor.

**Comment by platipodium** [comment]
> The fact that we have split the outputs into multiple pieces already violates UGRID, so I really don't see the point of overloading 3D outputs with metadata and static arrays (file size). It's more than sufficient to have this in out2d*.nc.

-  This PR only applies to scribed output, so it is not split into multiple pieces across CPUs.  Therefore, also the 3D files can be perfect UGRID/CF, if enriched with metadata.
- If we would automate quickviews in our data pipeline, we would either require metadata also in 3D, or intermediate post processing to copy the metadata from 2D to 3D and then visualise.  Effectively, this will be more waste of space.
- I suggest to introduce a parameter in `param.nml` iof_ugrid to take the values 0, 2, 3 for no, 2D, 3D enriched output, respectively, as default iof_ugrid=2.  There is also some possibility of space conservation by only doing node info and having face/edge info calculated online in the viz pipeline...

**Comment by platipodium** [comment]
> x,y units are not always lon, lat so this is misleading;

This has been taken care of by #d90df816d

**Comment by platipodium** [comment]
> Calculation of side/elem centers is wrong across lon jumps (that's why my scripts calculate these separately)

@josephzhang8 please fix the calculation or point me to a correct calculation

**Comment by josephzhang8** [comment]
Thx, Carsten. I like your suggestion of iof_ugrid as a compromise (even though adding deco into 3D outputs results in small increase for each, collectively they add up quickly).

Correct calculation of side/elem centers requires passing 3D coordinates (xnd,ynd,znd) to scribes. I'll do that in the future and for the time being, let's add a reminder there. Thx.

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by josephzhang8** [comment]
@Carsten: the new code is good enough and I'll go ahead and merge to master. We can continue to work on it afterward. With some many changes recently from different groups, it's better work directly in master for this type of changes that have minimal impact on others. Thx.

**Comment by josephzhang8** [comment]
Merged with git cmd.

**Pull request closed without merging**
