### PR TITLE
PAHM revision : Add support for GAHM + correction to support South Hemisphere

### PR DESCRIPTION
**Pull request by NeaLab-NC**
Hi ,
- Add GAHM (Generalized Asymmetric Holland Model) in PaHM/parwind.F90 as a second alternative to Holland Model
- Add support for Hurricanes in both South and North Hemisphere (in HM and GAHM models),
- Similar changes are PRequest to https://github.com/noaa-ocs-modeling/PaHM  
Cheers
Jerome (IRD noumea)

### CODE REVIEW

**Comment by josephzhang8** [comment]
@NeaLab-NC NeaLab-NC 
@soroosh.mani@noaa.gov

Many thanks, Jerome for adding GAHM! I see you mostly added asym GAHM formulation so it should not break backward compatibility (except for bug fixes for southern hemi). 

One question on 'modelType'. It's hard coded in PaHM_Utilities.F90 and we can consider making it a parameter input in the future. If someone wants to use '1' (Holland), they only need to reset this parameter to 1, correct?

I'll accept your changes, and will move the sample files to 'sample_inputs' for better organization. 

After we merge you probably want to refork or merge with the latest master before you push new changes. Thanks.

**Comment by josephzhang8** [comment]
I found info on 'modelType' in your readme. Thanks.

**Comment by josephzhang8** [comment]
@NeaLab-NC 

I just fixed a bug in _step related to modelType.

**Comment by jamal919** [comment]
Thanks to Jerome @NeaLab-NC , @takis, @josephzhang8   for implementing this input type, which is indeed quite convenient when forcing the model with advisories (a/b deck). Many storm surge modelling people might be immediately interested with this module, I believe.

I have two suggestions/questions in mind regarding PaHM (I presume its short for Parametric Holland Model) module - 

1. As there is no mention of PaHM in the documentation, the existence of this feature is quite hard to find as a beginner. As Jerome @NeaLab-NC  and @takis are well-versed in this module, would one of you can add a page under "module" with information about how to use it properly? That would be tremendously helpful.  I am guessing the SCHISM-PaHM is well-used at NOAA, and perhaps there already exists such guide. 
2. Secondly, I find it curious why PaHM code folder is stored inside the `Core` folder. For other modules with a folder structure (e.g., WWM, SED2D, SED3D etc.) seems to be stored under `/src`. Just curious. I am under impression that, if the PaHM folder gets its place under `/src` (instead of `/src/Core`) the code structure might be more visible? Although, it is just a cosmetic thing - nothing so important. 

Thanks again.

**Comment by josephzhang8** [comment]
RE 2: PaHM code is mostly written as modules, which need to be compiled first. All hydro codes that are modules are in Core/.


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Comment by NeaLab-NC** [comment]
@josephzhang8  , yes you are right about schism_step, fixed on my side too.
@jamal919 , add some minor indications in README.md on how to use schism-pahm. There are also links about PaHM and GAHM. A good fix should be to manage Core/pahm to read a pahm controlFile.in in order to set modelType, values for the background pressure etc....

**Comment by pvelissariou1** [comment]
Thank all and specifically Jerome. This is collaboration at its best. I have incorporated the changes in PaHM itself as well.
Basic PaHM documentation is online at: https://noaa-ocs-modeling.github.io/PaHM/html/index.html and the corresponding PDF version is located at: https://noaa-ocs-modeling.github.io/PaHM/pahm_manual.pdf

**Comment by josephzhang8** [comment]
Thx Takis for checking! I'll link the documentation to SCHISM manual also.


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Pull request merged**
